os: linux
dist: bionic
language: python
cache: pip
before_install:
  - sudo apt install software-properties-common
  #install firejail
  - sudo add-apt-repository -y ppa:deki/firejail
  - sudo apt-get update
  - sudo apt-get install firejail
  #install GCC
  - sudo apt-get install gcc

script:
  - "time firejail --private=playground ls"
  - pytest