# to run in VM
sudo: required
os: linux
language: generic
before_install:
  - sudo apt install software-properties-common
  #install firejail
  - sudo add-apt-repository -y ppa:deki/firejail
  - sudo apt-get update
  - sudo apt-get install firejail
  #install GCC
  - sudo apt-get install gcc
  #install python
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt install python3.7
  - sudo apt-get install python3-pip

before_script:
  - python3.7 -m pip install --upgrade pip
  - python3.7 -m pip install  setuptools
  - python3.7 -m pip install -r requirements.txt
script:
  - python3.7 -m pytest