# to run in VM
sudo: required
os: linux
language: python
before_install:
  #install firejail
  - sudo add-apt-repository -y ppa:deki/firejail
  - sudo apt-get update
  - sudo apt-get install firejail
  #install GCC
  - sudo apt-get install gcc
script:
  - pytest