# to run in VM
sudo: required
os: linux
language: generic
before_install:
  #install firejail
  - sudo add-apt-repository -y ppa:deki/firejail
  - sudo apt-get update
  - sudo apt-get install firejail
  #install GCC
  - sudo apt-get install gcc
  #install python
  - sudo apt-get install python3.6

before_script:
  - python3 -m pip install -r requirements.txt
script:
  - pytest